### ISSUE TITLE
TypeError: Cannot call method 'destroy' of undefined

### ISSUE THREAD

**Issue by Dieterbe** [cianclarke/node-gallery#6]
```
node app.js
node-gallery listening on localhost:3000
(...)
[exif.js] error in resources/photos/pc/cables_sata.jpg: {"message":"Number of entries greater than expected: 18761. Invalid EXIF?"}
[exif.js] error in resources/photos/pc/p4_doetbeetjeraar.jpg: {"message":"Number of entries greater than expected: 18761. Invalid EXIF?"}
[exif.js] error in resources/photos/pc/cables_serial_parrallel_etc.jpg: {"message":"Number of entries greater than expected: 18761. Invalid EXIF?"}

http.js:457
  this.socket.destroy(error);
              ^
TypeError: Cannot call method 'destroy' of undefined
    at ServerResponse.OutgoingMessage.destroy (http.js:457:15)
    at onclose (stream.js:74:10)
    at EventEmitter.emit (events.js:115:20)
    at ReadStream.destroy (fs.js:1374:12)
    at Object.oncomplete (fs.js:297:15)
```

interestingly, i've been navigating the site myself for a while now and everything seems to work, but this crash appeared shortly after I gave the link to somebody else

**Comment by cianclarke** [comment]
Closing - hoping the new release fixes this!
